server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=Agrimarket;encrypt=false;trustServerCertificate=true}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:Sql2026!}
    driver-class-name: ${DATABASE_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true